# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"

    resolvers:
        default:
            web_path: ~

    driver: "imagick"

    filter_sets:
        cache: ~
        thumb:
            quality: 85
            format: jpeg
            filters:
                upscale: { min: [600, 400]}
                thumbnail: { size: [600, 400], mode: outbound}
        mini:
            quality: 50
            format: webp
            filters:
                fixed: 
                    width: 180
                    height: 135
        gallery:
            format: jpeg
            filters:
                scale: { dim: [1000, 750]}
        static_thumb:
            quality: 75
            format: webp
            filters:
                fixed:
                    width: 500
                    height: 500


