vich_uploader:
    db_driver: orm

    mappings:
        event_thumbnail:
            uri_prefix: /images/thumbnails
            upload_destination: '%kernel.project_dir%/public/images/thumbnails'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        event_gallery:
            uri_prefix: /images/galleries
            upload_destination: '%kernel.project_dir%/public/images/galleries'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer