vich_uploader:
    db_driver: orm

    mappings:
        event_thumbnail:
            uri_prefix: /images/evenements
            upload_destination: '%kernel.project_dir%/public/images/evenements'
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        section_thumbnail:
            uri_prefix: /images/sections/
            upload_destination: '%kernel.project_dir%/public/images/sections'
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        event_gallery:
            uri_prefix: /images/galeries
            upload_destination: '%kernel.project_dir%/public/images/galeries'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer